project:
  type: website

website:
  title: "Froila M. Palmeiro"
  navbar:
    logo: "ssw.png"
    left:
      - icon: house
        href: index.qmd
        text: "Home"
      - text: "Research Topics" 
        menu:
          - href: stratospheric_variability.qmd
            text: Stratospheric Variability
          - href: nae.qmd
            text: NAE
          - href: enso.qmd
            text: ENSO
          - href: app.qmd
            text: QBO
      - href: publications.qmd
        text: "Publications"
      - text: "Project SD4SP"
        href: sd4sp_project.qmd
      - text: "Interactive Apps"
        menu:
          - href: ssw_app.qmd
            text: Extreme Stratospheric Events (SSWs & SPVs)
          - href: app.qmd
            text: QBO app
          - href: enso.qmd
            text: ENSO
    right:
      - icon: github
        href: https://github.com/Froila-science

  # MOVEMOS EL TRADUCTOR AQUÍ (Pie de página) PARA QUE NO DE ERROR
  page-footer:
    left: |
      <div id="google_translate_element"></div>
      <script type="text/javascript">
        function googleTranslateElementInit() {
          new google.translate.TranslateElement({
            pageLanguage: 'en', 
            includedLanguages: 'es,en,it,ca', 
            layout: google.translate.TranslateElement.InlineLayout.SIMPLE
          }, 'google_translate_element');
        }
      </script>
      <script type="text/javascript" src="//translate.google.com/translate_a/element.js?cb=googleTranslateElementInit"></script>
    right: "SD4SP Project | GA:101065820"

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: styles.css
    fontsize: 1.1em
    linestretch: 1.5
    toc: true
    toc-depth: 3
    toc-location: left
    code-copy: true
    anchor-sections: true
    smooth-scroll: true
