project:
  type: website

website:
  title: "Froila M. Palmeiro"
  logo: "sd4sp_logo_noback.png"
  navbar:
    left:
      - icon: house
        href: index.qmd
        text: "Home"
      - href: research.qmd
        text: "Research Topics" 
      - href: publications.qmd
        text: "Publications"
      - text: "Project SD4SP"
        href: sd4sp_project.qmd
      - href: app.qmd
        text: Interactive App
      - href: results.qmd
        text: Results
                
    right:
      - icon: github
        href: https://github.com/TU_USUARIO  # Tu perfil

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    fontsize: 1.1em
    linestretch: 1.5
    toc: true
    toc-depth: 3
    toc-location: left  # Mueve el índice a la izquierda para que parezca un libro técnico
    code-copy: true     # Botón para que la gente copie tus fórmulas/código
    anchor-sections: true
    smooth-scroll: true
     
