project:
  type: website

website:
  title: "Froila M. Palmeiro"
  navbar:
    left:
      - href: index.qmd
        text: Start
      - href: meteo.qmd
        text: Topics (Stratosphere, QBO, ENSO, SSWs)
      - href: app.qmd
        text: Interactive App
      - href: results.qmd
        text: Results

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    fontsize: 1.1em
    linestretch: 1.5
    toc: true
    toc-depth: 3
    toc-location: left  # Mueve el índice a la izquierda para que parezca un libro técnico
    code-copy: true     # Botón para que la gente copie tus fórmulas/código
    anchor-sections: true
    smooth-scroll: true
