---
title: "Publications"
---

### Manuscripts in Preparation & Under Review

* **Palmeiro, F. M.**, B. Mezzina, and J. García-Serrano. *The ENSO modulation of the 3-dimensional structure of the stratospheric polar vortex*. (To be submitted to **Nature Geoscience**).
* **Palmeiro, F. M.**, J. A. Anstey, and QBOi co-authors. *QBO-resolving model biases and their impacts on the extratropical teleconnections*. (In preparation).
* Sun, L., **F. M. Palmeiro**, and M. Jucker. *Stratosphere Relays El Niño’s Cross-continental Teleconnection from Winter North America to Early-summer Eurasia*. (In preparation).
* Blanco-Cabanillas, A., R. K. Scharien, S. E. L. Howell, and **F. M. Palmeiro**. *Sea ice regime shifts in Baffin Bay in the context of multi-decadal atmospheric variability*. (In preparation).
* **Palmeiro, F. M.**, A. Sanna, P. A., and S. Gualdi. *The impact of a better solved stratosphere in the CMCC seasonal prediction system*. (In preparation).
* Andrews, M. B., N. Butchart, ..., **F. M. Palmeiro**, et al. *Extratropical teleconnections in a multi-model ensemble nudged towards the observed QBO*. **Weather Clim. Dyn.** (Under review).
* Rodrigo, M., J. L. García-Franco, J. García-Serrano, I. Bladé, and **F. M. Palmeiro**. *Mechanisms of the QBO influence on the tropical troposphere: modulation by ENSO conditions*. **J. Geophys. Res.: Atmos.** (Under review).

---

### Peer-Reviewed Journal Articles

**2025**
* Rodrigo, M., J. L. García-Franco, J. García-Serrano, I. Bladé, and **F. M. Palmeiro**. (2025). Mechanisms of the QBO influence on the tropical troposphere: modulation by ENSO conditions. *J. Geophys. Res.: Atmos.* (Accepted).
* **Palmeiro, F. M.**, P. Hitchcock, and J. García-Serrano. (2025). Separating Multi-decadal and Interannual dynamics in the Tropical Pacific Ocean and their stratospheric teleconnections. *Geophysical Research Letters*. [{{< bi link-45deg >}} DOI](https://doi.org/10.1029/2025GL116639)
* Elsbury, D., ..., **F. M. Palmeiro**, et al. (2025). QBOi El Niño Southern Oscillation experiments: Assessing relationships between ENSO, MJO, and QBO. *Weather Clim. Dyn.*
* Rodrigo, M., J. L. García-Franco, J. García-Serrano, I. Bladé, and **F. M. Palmeiro**. (2025). Mechanisms of the QBO influence on the tropical troposphere: climatological SST conditions. *J. Geophys. Res.: Atmos.*
* Naoe, H., ..., **F. M. Palmeiro**, et al. (2025). QBOi El Niño Southern Oscillation experiments: Teleconnections of the QBO. *Weather Clim. Dyn.*
* Kawatani, Y., ..., **F. M. Palmeiro**, et al. (2025). QBOi El Niño Southern Oscillation experiments Part I: Overview of experiment design and ENSO modulation of the QBO. *Weather Clim. Dyn.*
* Mezzina, B., **F. M. Palmeiro**, H. Goosse, and J. A. Anstey. (2025). Impact of stratospheric polar vortex variability on Antarctic sea ice. *Climate Dynamics*.
* Garfinkel, C. I., ..., **F. M. Palmeiro**, et al. (2025). A process-based evaluation of biases in extratropical stratosphere-troposphere coupling in subseasonal forecast systems. *Weather Clim. Dyn.*
* Mudhar, R., A. Hall, J. Huang, R. W. Lee, and **F. M. Palmeiro**. (2025). QBOi-SNAP-QUOCA (QSQ) Workshop meeting report. *APARC newsletter / Weather*.

**2024**
* Volpi, D., J. García-Serrano, **F. M. Palmeiro**, L. Gil-Reyes, and R. J. Haarsma. (2024). Tropical Atlantic variability in EC-EARTH: impact of the radiative forcing. *Climate Dynamics*, 62, 5467–548.

**2023**
* **Palmeiro, F. M.**, J. García-Serrano, P. Ruggieri, L. Batté, and S. Gualdi. (2023). On the influence of ENSO on sudden stratospheric warmings. *JGR: Atmospheres*.

**2022**
* **Palmeiro, F. M.**, J. García-Serrano, M. Rodrigo, M. Abalos, B. Christiansen, and S. Yang. (2022). Boreal winter stratospheric climatology: CMIP6 version. *Climate Dynamics*, 60, 883–898.
* Lawrence, Z. D., ..., **F. M. Palmeiro**, et al. (2022). Quantifying stratospheric biases and identifying their potential sources in subseasonal prediction systems. *Weather Clim. Dyn.*, 3, 977-1001.

**2021**
* Mezzina, B., **F. M. Palmeiro**, J. García-Serrano, I. Bladé, L. Batté, and M. Benassi. (2021). Multi-model assessment of the late-winter stratospheric response to El Niño and La Niña. *Climate Dynamics*.
* Benassi, M., ..., **F. M. Palmeiro**, et al. (2021). ENSO teleconnection over the Euro-Mediterranean sector: the role of extratropical Pacific modulation. *Climate Dynamics*.
* Portal, A., P. Ruggieri, **F. M. Palmeiro**, J. García-Serrano, and S. Gualdi. (2021). Seasonal prediction of the boreal winter stratosphere. *Climate Dynamics*.

**2020**
* Stockdale, T., Y. H. Kim, J. Anstey, **F. M. Palmeiro**, et al. (2020). Prediction of the quasi-biennial oscillation with a multi-model ensemble of QBO-resolving models. *QJRMS*.
* Haarsma, R. J., ..., **F. M. Palmeiro**, et al. (2020). HighResMIP versions of EC-Earth: EC-Earth3P and EC-Earth3P-HR. *Geoscience Model Development*, 13, 3507–3527.
* Mezzina, B., J. García-Serrano, I. Bladé, **F. M. Palmeiro**, et al. (2020). Multi-model assessment of the late-winter extra-tropical response to El Niño and La Niña. *Climate Dynamics*.
* **Palmeiro, F. M.**, J. García-Serrano, O. Bellprat, P. A. Bretonnière, and F. J. Doblas-Reyes. (2020). Boreal winter stratospheric variability in EC‑EARTH: High‑Top versus Low‑Top. *Climate Dynamics*, 54, 3135–3150.

**2014 - 2019**
* Ayarzagüena, B., **F. M. Palmeiro**, D. Barriopedro, N. Calvo, et al. (2019). On the representation of major stratospheric warmings in reanalyses. *Atmospheric Chemistry and Physics*, 19, 9469-9484.
* **Palmeiro, F. M.**, M. Iza, D. Barriopedro, N. Calvo, and R. García-Herrera. (2017). The complex behaviour of El Niño winter 2015-2016. *Geophysical Research Letters*.
* **Palmeiro, F. M.**, D. Barriopedro, R. García-Herrera, and N. Calvo. (2015). Comparing Sudden Stratospheric Warming Definitions in Reanalysis Data. *Journal of Climate*, 28, 6823-6840.
* **Palmeiro, F. M.**, N. Calvo, and R. R. Garcia. (2014). Future changes in the Brewer Dobson circulation under different greenhouse gas concentrations. *Journal of Atmospheric Sciences*, 71(8), 2962-2975.

---

### Reports & Thesis

* Gerber, E. P., P. Martineau, ..., **F. M. Palmeiro**, et al. (2021). *Extratropical stratosphere-troposphere coupling*. S-RIP Final Report.
* **Palmeiro, F. M.** (2018). *Sudden Stratospheric Warmings and the Brewer-Dobson Circulation: diagnostics and interactions*. PhD Thesis, Universidad Complutense de Madrid. [{{< bi archive >}} Link](https://eprints.ucm.es/id/eprint/48270/)

<style>
  p {
    text-align: justify;
  }
</style>
